[package]
name = "bakexp_contracts"
version = "0.1.0"
description = "BakeXP Cairo 2 smart contracts for XP, Milestone NFTs, and BakePods."
edition = "2024_07"

[dependencies]
starknet = "2.11.4"
openzeppelin = "2.0.0"

[dev-dependencies]
snforge_std = "0.44.0"
assert_macros = "2.11.4"

[[target.starknet-contract]]
sierra = true
casm = true

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]